-- 31 - Join
CREATE TABLE DATOS(
	ID_DATOS INT,
	ID_ALUMNO INT,
	MAIL VARCHAR(30),
	EDAD INT
	CONSTRAINT PK_DATOS PRIMARY KEY (ID_DATOS)
	CONSTRAINT FK_ALUMNOS FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNOS(ID_ALUMNO)
);

CREATE TABLE ALUMNOS(
	ID_ALUMNO INT,
	NOMBRES VARCHAR(50),
	APELLIDOS VARCHAR(50),
	ID_CARRERA INT
	CONSTRAINT PF_ALUMNOS PRIMARY KEY (ID_ALUMNO)
	CONSTRAINT FK_CARRERAS FOREIGN KEY (ID_CARRERA) REFERENCES CARRERAS (ID_CARRERA)
);

CREATE TABLE CARRERAS(
	ID_CARRERA INT,
	NOMBRE VARCHAR(50)
	CONSTRAINT PK_CARRERAS PRIMARY KEY (ID_CARRERA)
);

INSERT INTO CARRERAS VALUES (1, 'Ing. Sistemas'), (2, 'Lic. Derecho'), (3, 'Lic. Administración');
INSERT INTO ALUMNOS VALUES (1, 'David', 'Hernandez Perez', 1), (2, 'Mariana', 'Martinez Luna', 2),(3, 'Tatiana', 'Ramirez Ramirez', 1),(4, 'Jose', 'Hackro', 3);
INSERT INTO DATOS VALUES (1, 1, 'hackro@yahoo.com', 22), (2, 2, 'mariana@gmail.com', 14), (3, 3, 'tatiana@gmail.com', 21), (4, 4, 'jose@gmail.com', 28);

SELECT * FROM ALUMNOS;
SELECT * FROM CARRERAS;
SELECT * FROM DATOS;

--32 - Inner Join

--Mostrar el email, la edad, nombre y la carreraa la cual pertenecen todos los alumnos

SELECT D.MAIL, D.EDAD, A.NOMBRES, C.NOMBRE
FROM DATOS D, ALUMNOS A, CARRERAS C
WHERE D.ID_ALUMNO = A.ID_ALUMNO
	AND A.ID_CARRERA = C.ID_CARRERA;

SELECT D.MAIL, D.EDAD, A.NOMBRES, C.NOMBRE
FROM DATOS D JOIN ALUMNOS A ON D.ID_ALUMNO = A.ID_ALUMNO
JOIN CARRERAS C ON A.ID_CARRERA = C.ID_CARRERA;

-- 33 - Join Left
--Busca los registros en la tabla izquierda
SELECT * FROM DATOS D LEFT JOIN ALUMNOS A ON D.ID_ALUMNO = A.ID_ALUMNO;
SELECT * FROM ALUMNOS A LEFT JOIN DATOS D ON D.ID_ALUMNO = A.ID_ALUMNO;


-- 34 - Right Join

SELECT * FROM DATOS D RIGHT JOIN ALUMNOS A ON D.ID_ALUMNO = A.ID_ALUMNO;
SELECT * FROM ALUMNOS A RIGHT JOIN DATOS D ON D.ID_ALUMNO = A.ID_ALUMNO;

-- 35 - Join and Group by
--puedo convianar los left join con lo inner noin y los rigth join
--usar Group by

-- 36 - Join and Update and Delete
--Actualizar el nombre de todos los alumnos de sistemas

SELECT * FROM ALUMNOS;

UPDATE ALUMNOS SET NOMBRES = 'Nombre Nuevo'
FROM ALUMNOS A JOIN CARRERAS C
ON A.ID_CARRERA = C.ID_CARRERA
WHERE C.ID_CARRERA = 1;

DELETE ALUMNOS
FROM ALUMNOS A JOIN CARRERAS C
ON A.ID_CARRERA = C.ID_CARRERA
WHERE C.ID_CARRERA = 1;