-- 37 - Alter Table
SELECT * FROM CARRERAS;

ALTER TABLE CARRERAS
ADD CUPO_LIMITADO INT 

ALTER TABLE CARRERAS
DROP COLUMN CUPO_LIMITADO;

ALTER TABLE CARRERAS
CHECK ID_CARRERA > 0 AND ID_CARRERA <1000;

-- 38 - Campos Calculados

--Aplica para los nuevos registros
--no puedo borrar la columna de referencia mientras exista la columna creada
ALTER TABLE CARRERAS
ADD CUPO_MINIMO INT; 
ALTER TABLE CARRERAS
ADD CUPO_LIMITADO INT;

ALTER TABLE CARRERAS
DROP COLUMN RESTA;

SELECT * FROM CARRERAS;

ALTER TABLE CARRERAS
ADD RESTA AS (CUPO_MINIMO + 100);

ALTER TABLE CARRERAS 
ADD OTRA AS ( CUPO_LIMITADO - 100);



